# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Communi-tea"
description: > # this means to ignore newlines until "email:"
   People and tech. Earl Grey, hot.

email: mayhens@gmail.com
#blog logo
logo: "/assets/images/communitea_logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/communitea_cover.jpg"

name: 'Monica Ayhens-Madon'
author: 'Monica Ayhens-Madon'
author_image: "/assets/images/MonicaBlog.jpg"

paginate:	5

url: "http://www.communi-tea.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@peripateticacad'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/peripateticacad
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/madhens
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

